version: '3'
services:
  flask:
    build:
      context: ./flask
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
  mongodb:
    build:
      context: ./mongodb
    volumes:
      - ./mongodb/db:/data/db
    ports:
      - "27017:27017"
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - "80:80"