version: '3'
services:
  flask:
    container_name: flask
    build:
      context: ./flask
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
  mongodb:
    container_name: mongodb
    build:
      context: ./mongodb
    volumes:
      - ./mongodb/db:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - flask